/**:
  ros__parameters:
    image_resize_height: 480
    num_blocks_horizontal: 5
    num_blocks_vertical: 5
    # Warning threshold
    shadow_region_warn_threshold: 10
    blockage_region_warn_threshold: 3
    low_visibility_region_warn_threshold: 2
    highlight_region_warn_threshold: 2
    # Error threshold
    shadow_region_error_threshold: 20
    blockage_region_error_threshold: 5
    low_visibility_region_error_threshold: 4
    highlight_region_error_threshold: 3

    blockage_ratio_threshold: 0.9
    blockage_intensity_threshold: 10
    blockage_frequency_ratio_threshold: 0.3

    shadow_intensity_threshold: 10
    low_visibility_frequency_threshold: 4.0
    highlight_intensity_threshold: 230
