/**:
  ros__parameters:
    # Plugin activation flags
    use_akima_spline_interpolation: false
    use_eb_smoother: false
    use_qp_smoother: true
    fix_invalid_points: true
    extend_trajectory_backward: false
