/**:
  ros__parameters:
    # QP Smoother Parameters
    # Path-only optimization: smooths geometric path (x,y positions)
    # Velocity/acceleration are derived from smoothed positions in post-processing

    # Optimization weights
    # Balance between smoothness and path fidelity
    # Note: High smoothness/fidelity ratio (100:1) allows path deviation for smoothness
    qp_weight_smoothness: 100.0                # Weight for path curvature minimization (geometric smoothness) [dimensionless]
    qp_weight_fidelity: 1.0                    # Weight for staying close to original path [dimensionless]

    # Time discretization
    qp_time_step_s: 0.1                        # Fixed time step for velocity/acceleration calculations [s]

    # OSQP solver settings (tuned for real-time performance)
    qp_osqp_eps_abs: 1.0e-4                    # Absolute tolerance for convergence
    qp_osqp_eps_rel: 1.0e-4                    # Relative tolerance for convergence
    qp_osqp_max_iter: 100                      # Maximum solver iterations
    qp_osqp_verbose: false                     # Print solver output to console

    # Orientation correction
    qp_fix_orientation: true               # Enable orientation correction
    qp_orientation_correction_threshold_deg: 5.0  # Yaw threshold for correcting QP output orientation [deg]
