/**:
  ros__parameters:
    # QP Smoother Parameters
    # Optimization weights
    # Balance between smoothness and path fidelity
    # Note: High curvature/fidelity ratio (1000:1) allows path deviation for smoothness
    qp_weight_jerk: 1000.0                     # Weight for path curvature minimization (smoothness) [dimensionless]
    qp_weight_acceleration: 0.0                # Weight for acceleration minimization (not used in path-only mode) [dimensionless]
    qp_weight_fidelity: 1.0                    # Weight for staying close to original path [dimensionless]

    # Dynamic constraints
    qp_max_longitudinal_jerk_mps3: 2.0         # Maximum longitudinal jerk [m/s³]
    qp_max_acceleration_mps2: 2.0              # Maximum acceleration [m/s²]
    qp_min_acceleration_mps2: -3.0             # Minimum acceleration (braking) [m/s²]
    qp_max_speed_mps: 20.0                     # Maximum speed [m/s]

    # OSQP solver settings (tuned for real-time performance)
    # Note: These values work well - 75 iterations, ~17cm avg path deviation
    qp_osqp_eps_abs: 1.0e-4                    # Absolute tolerance for convergence
    qp_osqp_eps_rel: 1.0e-4                    # Relative tolerance for convergence
    qp_osqp_max_iter: 100                      # Maximum solver iterations (typically solves in 50-100 iters)
    qp_osqp_verbose: false                     # Print solver output to console
