/**:
  ros__parameters:
    # ============================================================================
    # Camera Configuration
    # ============================================================================
    node_params:
      num_cameras: 6

    # ============================================================================
    # Image Processing and Detection Range
    # ============================================================================
    interface_params:
      # Image dimensions (CARLA/Bench2Drive → model input)
      input_image_width: 1600
      input_image_height: 900
      target_image_width: 640
      target_image_height: 384

      # Detection range [x_min, y_min, z_min, x_max, y_max, z_max] in base_link frame
      detection_range: [-30.0, -16.0, -0.355, 30.0, 16.0, 4.645]

      # Output trajectory configuration
      trajectory_timestep: 0.5  # [s]

    # ============================================================================
    # Model Configuration
    # ============================================================================
    model_params:
      # ImageNet normalization (RGB format)
      image_normalization_param_mean: [123.675, 116.28, 103.53]
      image_normalization_param_std: [58.395, 57.12, 57.375]

      # Class definitions (CARLA Tier4)
      map_class_names: ["Broken", "Solid", "SolidSolid", "Center", "TrafficLight", "StopSign"]
      object_class_names: ["car", "van", "truck", "bicycle", "traffic_sign", "traffic_cone", "traffic_light", "pedestrian", "others"]

      # ============================================================================
      # Neural Network Models
      # ============================================================================
      nets:
        backbone:
          name: "backbone"
          onnx_path: "$(var model_path)/vad-carla-tiny_backbone.onnx"
          engine_path: "$(var model_path)/vad-carla-tiny_backbone.engine"
          precision: "fp16"

        head:
          name: "head"
          onnx_path: "$(var model_path)/vad-carla-tiny_head.onnx"
          engine_path: "$(var model_path)/vad-carla-tiny_head.engine"
          precision: "fp32"
          inputs:
            "input_feature": "mlvl_feats.0"
            "net": "backbone"
            "name": "out.0"

        head_no_prev:
          name: "head_no_prev"
          onnx_path: "$(var model_path)/vad-carla-tiny_head_no_prev.onnx"
          engine_path: "$(var model_path)/vad-carla-tiny_head_no_prev.engine"
          precision: "fp32"
          inputs:
            "input_feature": "mlvl_feats.0"
            "net": "backbone"
            "name": "out.0"

      # ============================================================================
      # Network I/O Parameters
      # ============================================================================
      network_io_params:
        # BEV configuration
        bev_h: 106
        bev_w: 200
        bev_feature_dim: 256
        downsample_factor: 32

        # Transformer architecture
        num_decoder_layers: 3

        # Object prediction (detection + trajectory)
        prediction_num_queries: 300
        prediction_num_classes: 9
        prediction_bbox_pred_dim: 10  # [cx, cy, w, l, cz, h, sin, cos, vx, vy]
        prediction_trajectory_modes: 6
        prediction_timesteps: 6

        # Ego planning
        planning_ego_commands: 6
        planning_timesteps: 6

        # Map element detection
        map_num_queries: 100
        map_num_class: 6
        map_points_per_polylines: 20

        # Vehicle state
        can_bus_dim: 18
