/**:
  ros__parameters:
    default_position_z: 0.0
    default_velocity_z: 0.0
    default_acceleration_z: 0.0
    default_size_x: 5.0
    default_size_y: 2.0
    default_size_z: 2.0

    # classification remapping from RADAR to Perception
    # Format: [<RADAR label>, <Perception label>]
    classification_remap: [
      "UNKNOWN", "UNKNOWN",
      "CAR", "CAR",
      "TRUCK", "TRUCK",
      "MOTORCYCLE", "MOTORCYCLE",
      "BICYCLE", "BICYCLE",
      "PEDESTRIAN", "PEDESTRIAN",
      "ANIMAL", "ANIMAL",
      "HAZARD", "UNKNOWN"
    ]