/**:
  ros__parameters:
    class_names: ["CAR", "TRUCK", "BUS", "BICYCLE", "PEDESTRIAN"]
    voxels_num: [1, 128000, 256000] # [min, opt, max]
    point_cloud_range: [-122.4, -122.4, -3.0, 122.4, 122.4, 5.0] # [x_min, y_min, z_min, x_max, y_max, z_max]
    voxel_size: [0.17, 0.17, 0.2] # [x, y, z]
    num_proposals: 500
    out_size_factor: 8
    max_points_per_voxel: 10
    use_intensity: false

    d_bound: [1.0, 134.0, 1.4]
    x_bound: [-122.4, 122.4, 0.68]
    y_bound: [-122.4, 122.4, 0.68]
    z_bound: [-10.0, 10.0, 20.0]
    num_cameras: 6
    raw_image_height: 1080
    raw_image_width: 1440
    img_aug_scale_x: 0.4
    img_aug_scale_y: 0.4
    roi_height: 384
    roi_width: 576
    features_height: 48
    features_width: 72
    num_depth_features: 95
    image_feature_channel: 256

    detection_score_thresholds:
        # Upper bound of radial distance of 3d center_x and center_y in bounding boxes, and starting from 0
        # [0-50m), [50.0-90m), [90.0-121.0m), [121.0-200.0m), set a very high number for the last one to be safe
        distance_bin_upper_limits: [50.0, 90.0, 121.0, 200.0]
        # Each list of thresholds must match with the number of upper_bounds, and each threshold corresponds to a distance bucket in the order of the upper bounds
        min_confidence_scores:
          CAR: [0.15, 0.15, 0.15, 0.15]
          TRUCK: [0.15, 0.15, 0.15, 0.15]
          BUS: [0.15, 0.15, 0.15, 0.15]
          BICYCLE: [0.15, 0.15, 0.15, 0.15]
          PEDESTRIAN: [0.15, 0.15, 0.15, 0.15]
