/**:
  ros__parameters:
    roundabout:
      common:
        attention_area_length: 200.0
        attention_area_margin: 0.75
        attention_area_angle_threshold: 0.785
        use_roundabout_area: false
        default_stopline_margin: 1.5
        stopline_overshoot_margin: 0.5
        path_interpolation_ds: 0.1
        max_accel: -2.8
        max_jerk: -5.0
        delay_response_time: 0.5
        enable_pass_judge_before_default_stopline: false


      collision_detection:
        consider_wrong_direction_vehicle: false
        collision_detection_hold_time: 0.5
        min_predicted_path_confidence: 0.05
        target_type:
          car: true
          bus: true
          truck: true
          trailer: true
          motorcycle: true
          bicycle: true
          unknown: false
        velocity_profile:
          use_upstream: true
          minimum_upstream_velocity: 0.01
          default_velocity: 2.778
          minimum_default_velocity: 1.388
        fully_prioritized:
          collision_start_margin_time: 2.0
          collision_end_margin_time: 0.0
        partially_prioritized:
          collision_start_margin_time: 3.0
          collision_end_margin_time: 2.0
        not_prioritized:
          collision_start_margin_time: 3.0
          collision_end_margin_time: 2.0
        # yield_on_green_traffic_light:
        #   distance_to_assigned_lanelet_start: 10.0
        #   duration: 3.0
        #   object_dist_to_stopline: 10.0
        # ignore_on_amber_traffic_light:
        #   object_expected_deceleration:
        #     car: 2.0
        #     bike: 5.0
        # ignore_on_red_traffic_light:
        #   object_margin_to_path: 2.0
        avoid_collision_by_acceleration:
          object_time_margin_to_collision_point: 4.0

      debug:
        ttc: [0]

      enable_rtc:
        roundabout: false
